-- =============================================================================
-- 2026-06-09  Audi 1 / Audi 2 backfill cleanup + serial rebase  (SUPERSEDES the
-- in-place edits to 20260608100000, which the CLI will not re-run once that
-- version is recorded as applied). Fully idempotent — safe whether the earlier
-- version ran partially, fully, or not at all. Apply to STAGING first.
--
-- Confirmed on staging: 4 backfill (mh*) rows still sit in the live window
-- (>= 2026-04-30) after the earlier partial dedup, and serialStarts was never
-- rebased. This migration finishes both jobs:
--   1. restore any collided live rows still showing era keys / hist cards
--   2. remap 2026-05-30 (post-snapshot) in place
--   3. delete EVERY backfill row (mh + 8 hex) dated >= 2026-04-30
--   4. rebase config.data serialStarts to a single 2026-04-30 = 1 start/screen
--      (config.data is the app's authoritative read path — useSupabaseSync
--       builds state via applyConfigPayload(base, config.data))
-- Guards abort the whole migration if anything is left inconsistent.
-- =============================================================================

-- 1) Restore collided rows from the pre-backfill snapshot (no-op if already clean)
update public.entries e
set share = v.share, shows = v.shows,
    updated_by = 'backfill-overwrite-repair', updated_at = now()
from (values
  (date '2026-05-13', 'uhxgzpr', '7gwkvh9', 55, '[{"id":"kc0kh3o","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"de8fk1e"},{"id":"1397qi4","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:15","priceCardId":"de8fk1e"},{"id":"xbsnh2n","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"16:30","priceCardId":"de8fk1e"},{"id":"pxpopbj","rows":{"cls_prime":{"tickets":"324"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"18"}},"online":"","freePass":"","lastShow":false,"showtime":"18:30","priceCardId":"de8fk1e"},{"id":"d5djjnh","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:15","priceCardId":"de8fk1e"}]'::jsonb),
  (date '2026-05-14', 'uhxgzpr', '7gwkvh9', 55, '[{"id":"7v6ki84","rows":{"cls_prime":{"tickets":"125"},"cls_lounge":{"tickets":"90"},"cls_royale":{"tickets":"9"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"de8fk1e"},{"id":"glr0kgp","rows":{"cls_prime":{"tickets":"222"},"cls_lounge":{"tickets":"138"},"cls_royale":{"tickets":"11"}},"online":"","freePass":"","lastShow":false,"showtime":"13:15","priceCardId":"de8fk1e"},{"id":"607alv1","rows":{"cls_prime":{"tickets":"167"},"cls_lounge":{"tickets":"163"},"cls_royale":{"tickets":"15"}},"online":"","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"de8fk1e"},{"id":"jjmkcsj","rows":{"cls_prime":{"tickets":"296"},"cls_lounge":{"tickets":"165"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":false,"showtime":"19:35","priceCardId":"de8fk1e"},{"id":"yt85rtp","rows":{"cls_prime":{"tickets":"272"},"cls_lounge":{"tickets":"160"},"cls_royale":{"tickets":"18"}},"online":"","freePass":"","lastShow":true,"showtime":"22:50","priceCardId":"de8fk1e"}]'::jsonb),
  (date '2026-05-14', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"fcjrh66","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"f5ty1o4"},{"id":"13ftrk3","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"9dgq5v2","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"ms4k482","rows":{"1u1lpa4":{"tickets":"88"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"118"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"chzmd45","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-15', 'uhxgzpr', '7gwkvh9', 55, '[{"id":"mlpxh4m","rows":{"cls_prime":{"tickets":"80"},"cls_lounge":{"tickets":"46"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"de8fk1e"},{"id":"nekwe90","rows":{"cls_prime":{"tickets":"122"},"cls_lounge":{"tickets":"102"},"cls_royale":{"tickets":"11"}},"online":"","freePass":"","lastShow":false,"showtime":"13:15","priceCardId":"de8fk1e"},{"id":"dwzikz3","rows":{"cls_prime":{"tickets":"117"},"cls_lounge":{"tickets":"155"},"cls_royale":{"tickets":"14"}},"online":"","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"de8fk1e"},{"id":"jdpob1o","rows":{"cls_prime":{"tickets":"284"},"cls_lounge":{"tickets":"164"},"cls_royale":{"tickets":"19"}},"online":"","freePass":"","lastShow":false,"showtime":"19:35","priceCardId":"de8fk1e"},{"id":"ivr8qtu","rows":{"cls_prime":{"tickets":"141"},"cls_lounge":{"tickets":"118"},"cls_royale":{"tickets":"10"}},"online":"","freePass":"","lastShow":true,"showtime":"22:50","priceCardId":"de8fk1e"}]'::jsonb),
  (date '2026-05-15', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"55n451c","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"f5ty1o4"},{"id":"toddq1u","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"22ebmix","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"q9bbvoo","rows":{"1u1lpa4":{"tickets":"90"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"144"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"ua76eq9","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-16', 'uhxgzpr', '7gwkvh9', 55, '[{"id":"lqmfvqf","rows":{"cls_prime":{"tickets":"83"},"cls_lounge":{"tickets":"88"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"de8fk1e"},{"id":"vkznhkc","rows":{"cls_prime":{"tickets":"174"},"cls_lounge":{"tickets":"147"},"cls_royale":{"tickets":"12"}},"online":"","freePass":"","lastShow":false,"showtime":"13:15","priceCardId":"de8fk1e"},{"id":"lwtp6ic","rows":{"cls_prime":{"tickets":"142"},"cls_lounge":{"tickets":"159"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"de8fk1e"},{"id":"etbh7fa","rows":{"cls_prime":{"tickets":"222"},"cls_lounge":{"tickets":"165"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":false,"showtime":"19:35","priceCardId":"de8fk1e"},{"id":"45pz389","rows":{"cls_prime":{"tickets":"159"},"cls_lounge":{"tickets":"145"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":true,"showtime":"22:50","priceCardId":"de8fk1e"}]'::jsonb),
  (date '2026-05-16', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"s6h6o9b","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"f5ty1o4"},{"id":"vj0y58j","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"t25d8sz","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"0djot8o","rows":{"1u1lpa4":{"tickets":"88"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"123"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"5pu7hgo","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-17', 'uhxgzpr', '7gwkvh9', 55, '[{"id":"cizj3ai","rows":{"cls_prime":{"tickets":"113"},"cls_lounge":{"tickets":"125"},"cls_royale":{"tickets":"10"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"de8fk1e"},{"id":"ap9qc80","rows":{"cls_prime":{"tickets":"210"},"cls_lounge":{"tickets":"159"},"cls_royale":{"tickets":"10"}},"online":"","freePass":"","lastShow":false,"showtime":"13:15","priceCardId":"de8fk1e"},{"id":"tzdywh3","rows":{"cls_prime":{"tickets":"251"},"cls_lounge":{"tickets":"164"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"de8fk1e"},{"id":"kflxv8m","rows":{"cls_prime":{"tickets":"251"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"19:35","priceCardId":"de8fk1e"},{"id":"41himx5","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"22:50","priceCardId":"de8fk1e"}]'::jsonb),
  (date '2026-05-17', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"jjflmm2","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"f5ty1o4"},{"id":"it3u4zk","rows":{"1u1lpa4":{"tickets":"85"},"bsl9hd8":{"tickets":"2"},"lp9hi7s":{"tickets":"92"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"es27nyf","rows":{"1u1lpa4":{"tickets":"87"},"bsl9hd8":{"tickets":"1"},"lp9hi7s":{"tickets":"119"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"pw76yy4","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"ye4abry","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-18', 'uhxgzpr', '7gwkvh9', 55, '[{"id":"xnr0o19","rows":{"cls_prime":{"tickets":"69"},"cls_lounge":{"tickets":"54"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"de8fk1e"},{"id":"7qk2x1e","rows":{"cls_prime":{"tickets":"158"},"cls_lounge":{"tickets":"86"},"cls_royale":{"tickets":"7"}},"online":"","freePass":"","lastShow":false,"showtime":"13:15","priceCardId":"de8fk1e"},{"id":"5vt1sk9","rows":{"cls_prime":{"tickets":"75"},"cls_lounge":{"tickets":"96"},"cls_royale":{"tickets":"8"}},"online":"","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"de8fk1e"},{"id":"y924ebm","rows":{"cls_prime":{"tickets":"145"},"cls_lounge":{"tickets":"150"},"cls_royale":{"tickets":"9"}},"online":"","freePass":"","lastShow":false,"showtime":"19:35","priceCardId":"de8fk1e"},{"id":"djnmba0","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"22:50","priceCardId":"de8fk1e"}]'::jsonb),
  (date '2026-05-18', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"aatiteh","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"f5ty1o4"},{"id":"kidbnj3","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"qv759mg","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"khgdaat","rows":{"1u1lpa4":{"tickets":"41"},"bsl9hd8":{"tickets":"2"},"lp9hi7s":{"tickets":"13"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"0tvgeja","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-19', 'uhxgzpr', '7gwkvh9', 60, '[{"id":"3rmep90","rows":{"cls_prime":{"tickets":"68"},"cls_lounge":{"tickets":"41"},"cls_royale":{"tickets":"3"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"lo9ccuv"},{"id":"46huhxf","rows":{"cls_prime":{"tickets":"141"},"cls_lounge":{"tickets":"103"},"cls_royale":{"tickets":"6"}},"online":"","freePass":"","lastShow":false,"showtime":"12:45","priceCardId":"lo9ccuv"},{"id":"4d6gdit","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"15:50","priceCardId":"lo9ccuv"},{"id":"ej2dcyg","rows":{"cls_prime":{"tickets":"122"},"cls_lounge":{"tickets":"99"},"cls_royale":{"tickets":"13"}},"online":"","freePass":"","lastShow":false,"showtime":"18:45","priceCardId":"lo9ccuv"},{"id":"7rg9pg0","rows":{"cls_prime":{"tickets":"112"},"cls_lounge":{"tickets":"150"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":true,"showtime":"22:00","priceCardId":"lo9ccuv"}]'::jsonb),
  (date '2026-05-19', 'uhxgzpr', 'oxnv3cw', 60, '[{"id":"lf63lwr","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"f5ty1o4"},{"id":"4xuniom","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"we1lwq0","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"akqrne9","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"ahgg6b0","rows":{"1u1lpa4":{"tickets":"58"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"46"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-20', 'uhxgzpr', '7gwkvh9', 60, '[{"id":"n1nqvin","rows":{"cls_prime":{"tickets":"43"},"cls_lounge":{"tickets":"56"},"cls_royale":{"tickets":"1"}},"online":"","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"lo9ccuv"},{"id":"qbgg8t4","rows":{"cls_prime":{"tickets":"106"},"cls_lounge":{"tickets":"91"},"cls_royale":{"tickets":"6"}},"online":"","freePass":"","lastShow":false,"showtime":"12:45","priceCardId":"lo9ccuv"},{"id":"aw5b05q","rows":{"cls_prime":{"tickets":"0"},"cls_lounge":{"tickets":"0"},"cls_royale":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"15:50","priceCardId":"lo9ccuv"},{"id":"iur3yu5","rows":{"cls_prime":{"tickets":"95"},"cls_lounge":{"tickets":"114"},"cls_royale":{"tickets":"5"}},"online":"","freePass":"","lastShow":false,"showtime":"18:45","priceCardId":"lo9ccuv"},{"id":"r7y7iyn","rows":{"cls_prime":{"tickets":"116"},"cls_lounge":{"tickets":"133"},"cls_royale":{"tickets":"16"}},"online":"","freePass":"","lastShow":true,"showtime":"22:00","priceCardId":"lo9ccuv"}]'::jsonb),
  (date '2026-05-21', '26ammug', '7gwkvh9', 60, '[{"id":"3l21pct","rows":{"cls_prime":{"tickets":"412"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"16"}},"online":"","freePass":"","lastShow":false,"showtime":"08:00","priceCardId":"18a8omq"},{"id":"b3qlftx","rows":{"cls_prime":{"tickets":"387"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"11:15","priceCardId":"qs31yg4"},{"id":"2zheoqa","rows":{"cls_prime":{"tickets":"403"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"14:20","priceCardId":"qs31yg4"},{"id":"9lmg3tl","rows":{"cls_prime":{"tickets":"412"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"17:30","priceCardId":"qs31yg4"},{"id":"0evkdx0","rows":{"cls_prime":{"tickets":"412"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"qs31yg4"},{"id":"3t74vr3","rows":{"cls_prime":{"tickets":"396"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":true,"showtime":"23:59","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-21', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"qy5kwcr","rows":{"1u1lpa4":{"tickets":"38"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"19"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"se39su5","rows":{"1u1lpa4":{"tickets":"66"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"54"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"i4is3ne","rows":{"1u1lpa4":{"tickets":"57"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"37"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"8gx4ejx","rows":{"1u1lpa4":{"tickets":"88"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"110"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"50636rx","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-22', '26ammug', '7gwkvh9', 60, '[{"id":"b28fjui","rows":{"cls_prime":{"tickets":"54"},"cls_lounge":{"tickets":"86"},"cls_royale":{"tickets":"4"}},"online":"","freePass":"","lastShow":false,"showtime":"08:00","priceCardId":"qs31yg4"},{"id":"zdmt9ai","rows":{"cls_prime":{"tickets":"352"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"11:15","priceCardId":"qs31yg4"},{"id":"scahrer","rows":{"cls_prime":{"tickets":"392"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"14:20","priceCardId":"qs31yg4"},{"id":"rz6rmo8","rows":{"cls_prime":{"tickets":"382"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"17:30","priceCardId":"qs31yg4"},{"id":"kx3og5b","rows":{"cls_prime":{"tickets":"407"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"qs31yg4"},{"id":"pugtwck","rows":{"cls_prime":{"tickets":"346"},"cls_lounge":{"tickets":"165"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":true,"showtime":"23:59","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-22', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"sov6jpo","rows":{"1u1lpa4":{"tickets":"28"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"19"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"0hu23bp","rows":{"1u1lpa4":{"tickets":"60"},"bsl9hd8":{"tickets":"1"},"lp9hi7s":{"tickets":"39"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"3e11ed7","rows":{"1u1lpa4":{"tickets":"56"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"30"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"ntbnvuj","rows":{"1u1lpa4":{"tickets":"88"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"90"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"7vtglgd","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-23', '26ammug', '7gwkvh9', 60, '[{"id":"d4vv90z","rows":{"cls_prime":{"tickets":"80"},"cls_lounge":{"tickets":"93"},"cls_royale":{"tickets":"10"}},"online":"","freePass":"","lastShow":false,"showtime":"08:00","priceCardId":"qs31yg4"},{"id":"20112ar","rows":{"cls_prime":{"tickets":"352"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"11:15","priceCardId":"qs31yg4"},{"id":"tt7prux","rows":{"cls_prime":{"tickets":"408"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"14:20","priceCardId":"qs31yg4"},{"id":"sbxinyh","rows":{"cls_prime":{"tickets":"396"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"17:30","priceCardId":"qs31yg4"},{"id":"581qc5z","rows":{"cls_prime":{"tickets":"411"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"qs31yg4"},{"id":"08r6mkz","rows":{"cls_prime":{"tickets":"356"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":true,"showtime":"23:59","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-23', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"rqb0lhy","rows":{"1u1lpa4":{"tickets":"48"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"25"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"v7ldmja","rows":{"1u1lpa4":{"tickets":"70"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"38"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"b2l4twi","rows":{"1u1lpa4":{"tickets":"83"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"39"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"zd8e0d3","rows":{"1u1lpa4":{"tickets":"90"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"113"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"0ml6vx4","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-24', '26ammug', '7gwkvh9', 60, '[{"id":"22h00v8","rows":{"cls_prime":{"tickets":"167"},"cls_lounge":{"tickets":"163"},"cls_royale":{"tickets":"19"}},"online":"","freePass":"","lastShow":false,"showtime":"08:00","priceCardId":"qs31yg4"},{"id":"3tig9fb","rows":{"cls_prime":{"tickets":"395"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"11:15","priceCardId":"qs31yg4"},{"id":"bltzi0q","rows":{"cls_prime":{"tickets":"411"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"14:20","priceCardId":"qs31yg4"},{"id":"fve4gr3","rows":{"cls_prime":{"tickets":"404"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"17:30","priceCardId":"qs31yg4"},{"id":"n1kspy5","rows":{"cls_prime":{"tickets":"412"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"qs31yg4"},{"id":"e6et3lf","rows":{"cls_prime":{"tickets":"305"},"cls_lounge":{"tickets":"165"},"cls_royale":{"tickets":"19"}},"online":"","freePass":"","lastShow":true,"showtime":"23:59","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-24', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"juf9sp7","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"wgudlsp","rows":{"1u1lpa4":{"tickets":"74"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"53"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"opn8xf4","rows":{"1u1lpa4":{"tickets":"88"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"102"}},"online":"","freePass":"","lastShow":false,"showtime":"17:00","priceCardId":"f5ty1o4"},{"id":"e7ckty9","rows":{"1u1lpa4":{"tickets":"87"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"105"}},"online":"","freePass":"","lastShow":false,"showtime":"20:45","priceCardId":"f5ty1o4"},{"id":"72eed4c","rows":{"1u1lpa4":{"tickets":"83"},"bsl9hd8":{"tickets":"1"},"lp9hi7s":{"tickets":"25"}},"online":"","freePass":"","lastShow":true,"showtime":"23:35","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-25', '26ammug', '7gwkvh9', 60, '[{"id":"95djmuq","rows":{"cls_prime":{"tickets":"248"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":false,"showtime":"08:00","priceCardId":"qs31yg4"},{"id":"7ekeuad","rows":{"cls_prime":{"tickets":"353"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":false,"showtime":"11:15","priceCardId":"qs31yg4"},{"id":"n9dfnes","rows":{"cls_prime":{"tickets":"313"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"14:20","priceCardId":"qs31yg4"},{"id":"9pggni5","rows":{"cls_prime":{"tickets":"374"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":false,"showtime":"17:30","priceCardId":"qs31yg4"},{"id":"9rieb5r","rows":{"cls_prime":{"tickets":"152"},"cls_lounge":{"tickets":"163"},"cls_royale":{"tickets":"20"}},"online":"","freePass":"","lastShow":true,"showtime":"20:45","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-25', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"js4nw0z","rows":{"1u1lpa4":{"tickets":"4"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"9"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"hybfb90","rows":{"1u1lpa4":{"tickets":"26"},"bsl9hd8":{"tickets":"1"},"lp9hi7s":{"tickets":"34"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"8lxpdtz","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"16:00","priceCardId":"f5ty1o4"},{"id":"ke119ko","rows":{"1u1lpa4":{"tickets":"62"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"31"}},"online":"","freePass":"","lastShow":false,"showtime":"19:05","priceCardId":"f5ty1o4"},{"id":"kj61l7f","rows":{"1u1lpa4":{"tickets":"16"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"9"}},"online":"","freePass":"","lastShow":true,"showtime":"22:15","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-26', '26ammug', '7gwkvh9', 60, '[{"id":"vtg7jma","rows":{"cls_prime":{"tickets":"298"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"77820","freePass":"","lastShow":false,"showtime":"17:15","priceCardId":"qs31yg4"},{"id":"f5cpn1u","rows":{"cls_prime":{"tickets":"378"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"92930","freePass":"","lastShow":false,"showtime":"20:35","priceCardId":"qs31yg4"},{"id":"1jhqei2","rows":{"cls_prime":{"tickets":"123"},"cls_lounge":{"tickets":"140"}},"online":"36560","freePass":"","lastShow":true,"showtime":"23:45","priceCardId":"qs31yg4"},{"id":"2ekpz6e","rows":{"cls_prime":{"tickets":"216"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"10:45","priceCardId":"qs31yg4"},{"id":"h2y5kgn","rows":{"cls_prime":{"tickets":"303"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"","freePass":"","lastShow":false,"showtime":"14:00","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-26', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"puhmr34","rows":{"1u1lpa4":{"tickets":"6"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"11"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"m9tyr68","rows":{"1u1lpa4":{"tickets":"37"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"18"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"2d9k20e","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"16:00","priceCardId":"f5ty1o4"},{"id":"8czbzx1","rows":{"1u1lpa4":{"tickets":"72"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"11"}},"online":"","freePass":"","lastShow":false,"showtime":"19:05","priceCardId":"f5ty1o4"},{"id":"mrb4wf1","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"22:15","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-27', '26ammug', '7gwkvh9', 60, '[{"id":"gvwd5ub","rows":{"cls_prime":{"tickets":"180"},"cls_lounge":{"tickets":"164"},"cls_royale":{"tickets":"17"}},"online":"59750","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"qs31yg4"},{"id":"y971xw8","rows":{"cls_prime":{"tickets":"273"},"cls_lounge":{"tickets":"164"},"cls_royale":{"tickets":"20"}},"online":"70080","freePass":"","lastShow":false,"showtime":"13:10","priceCardId":"qs31yg4"},{"id":"q0j9r2n","rows":{"cls_prime":{"tickets":"292"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"80330","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"qs31yg4"},{"id":"44uqyrh","rows":{"cls_prime":{"tickets":"301"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"83670","freePass":"","lastShow":false,"showtime":"19:30","priceCardId":"qs31yg4"},{"id":"1qeeoj5","rows":{"cls_prime":{"tickets":"230"},"cls_lounge":{"tickets":"161"},"cls_royale":{"tickets":"20"}},"online":"70220","freePass":"","lastShow":true,"showtime":"22:45","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-27', 'uhxgzpr', 'oxnv3cw', 55, '[{"id":"0twhmxm","rows":{"1u1lpa4":{"tickets":"42"},"bsl9hd8":{"tickets":"1"},"lp9hi7s":{"tickets":"19"}},"online":"","freePass":"","lastShow":false,"showtime":"11:00","priceCardId":"f5ty1o4"},{"id":"54rtxsc","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"13:25","priceCardId":"f5ty1o4"},{"id":"3reab5z","rows":{"1u1lpa4":{"tickets":"54"},"bsl9hd8":{"tickets":"1"},"lp9hi7s":{"tickets":"10"}},"online":"","freePass":"","lastShow":false,"showtime":"16:00","priceCardId":"f5ty1o4"},{"id":"a92udmr","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":false,"showtime":"19:05","priceCardId":"f5ty1o4"},{"id":"sk8e5tu","rows":{"1u1lpa4":{"tickets":"0"},"bsl9hd8":{"tickets":"0"},"lp9hi7s":{"tickets":"0"}},"online":"","freePass":"","lastShow":true,"showtime":"22:15","priceCardId":"f5ty1o4"}]'::jsonb),
  (date '2026-05-28', '26ammug', '7gwkvh9', 55, '[{"id":"7xjkauw","rows":{"cls_prime":{"tickets":"142"},"cls_lounge":{"tickets":"156"},"cls_royale":{"tickets":"17"}},"online":"49810","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"qs31yg4"},{"id":"6mzaz7v","rows":{"cls_prime":{"tickets":"241"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"68080","freePass":"","lastShow":false,"showtime":"13:10","priceCardId":"qs31yg4"},{"id":"wgysohv","rows":{"cls_prime":{"tickets":"300"},"cls_lounge":{"tickets":"164"},"cls_royale":{"tickets":"21"}},"online":"78470","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"qs31yg4"},{"id":"uvid6j2","rows":{"cls_prime":{"tickets":"331"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"21"}},"online":"88310","freePass":"","lastShow":false,"showtime":"19:30","priceCardId":"qs31yg4"},{"id":"vsifxpk","rows":{"cls_prime":{"tickets":"268"},"cls_lounge":{"tickets":"165"},"cls_royale":{"tickets":"20"}},"online":"77020","freePass":"","lastShow":true,"showtime":"22:45","priceCardId":"qs31yg4"}]'::jsonb),
  (date '2026-05-29', '26ammug', '7gwkvh9', 55, '[{"id":"zass8ij","rows":{"cls_prime":{"tickets":"66"},"cls_lounge":{"tickets":"100"},"cls_royale":{"tickets":"4"}},"online":"23340","freePass":"","lastShow":false,"showtime":"10:00","priceCardId":"qs31yg4"},{"id":"o5l1ure","rows":{"cls_prime":{"tickets":"153"},"cls_lounge":{"tickets":"165"},"cls_royale":{"tickets":"16"}},"online":"49440","freePass":"","lastShow":false,"showtime":"13:10","priceCardId":"qs31yg4"},{"id":"jm6b3g6","rows":{"cls_prime":{"tickets":"204"},"cls_lounge":{"tickets":"158"},"cls_royale":{"tickets":"21"}},"online":"63330","freePass":"","lastShow":false,"showtime":"16:20","priceCardId":"qs31yg4"},{"id":"npi77be","rows":{"cls_prime":{"tickets":"326"},"cls_lounge":{"tickets":"166"},"cls_royale":{"tickets":"20"}},"online":"84060","freePass":"","lastShow":false,"showtime":"19:37","priceCardId":"qs31yg4"},{"id":"2g8t63r","rows":{"cls_prime":{"tickets":"168"},"cls_lounge":{"tickets":"163"},"cls_royale":{"tickets":"16"}},"online":"55420","freePass":"","lastShow":true,"showtime":"22:45","priceCardId":"18a8omq"}]'::jsonb)
) as v(entry_date, movie_id, screen_id, share, shows)
where e.entry_date = v.entry_date and e.movie_id = v.movie_id and e.screen_id = v.screen_id
  and (e.updated_by = 'dcr-historical-import'
       or e.shows::text like '%a1_rc_%'
       or e.shows::text ~ '"(h159175|h61c20e|hed0d4a|hba8c16)"');

-- 2) Remap 2026-05-30 era keys/cards in place (no-op if already remapped)
update public.entries
set shows = replace(replace(replace(replace(shows::text,
              '"a1_rc_lng"','"cls_lounge"'),'"a1_rc_prm"','"cls_prime"'),
              '"hec1e84"','"qs31yg4"'),'"h90aa57"','"18a8omq"')::jsonb,
    updated_by = 'backfill-overwrite-repair', updated_at = now()
where entry_date = date '2026-05-30' and movie_id = '26ammug' and screen_id = '7gwkvh9'
  and shows::text like '%a1_rc_%';

-- 3) Delete EVERY backfill row in the live window (catches the last 4 stragglers)
delete from public.entries
where movie_id ~ '^mh[0-9a-f]{8}$' and entry_date >= date '2026-04-30';

-- 4) Rebase serial numbering to 2026-04-30 = 1 per screen (authoritative blob)
update public.config
set data = jsonb_set(data, '{serialStarts}', '[{"id": "e4ujqqp", "date": "2026-04-30", "starts": {"cls_royale": 1, "cls_lounge": 1, "cls_prime": 1}, "screenId": "7gwkvh9"}, {"id": "m8xbwh8", "date": "2026-04-30", "starts": {"1u1lpa4": 1, "lp9hi7s": 1, "bsl9hd8": 1}, "screenId": "oxnv3cw"}]'::jsonb),
    updated_by = 'backfill-overwrite-repair', updated_at = now()
where id = 1;

-- 5) Guards
do $$
declare n int;
begin
  select count(*) into n from public.entries
   where screen_id='7gwkvh9' and entry_date between date '2026-05-13' and date '2026-05-31'
     and shows::text like '%a1_rc_%';
  if n>0 then raise exception 'incomplete: % Audi 1 rows still carry era keys', n; end if;

  select count(*) into n from public.entries
   where screen_id='oxnv3cw' and entry_date between date '2026-05-14' and date '2026-05-27'
     and shows::text ~ '"(h159175|h61c20e)"';
  if n>0 then raise exception 'incomplete: % Audi 2 rows still carry hist cards', n; end if;

  select count(*) into n from public.entries
   where movie_id ~ '^mh[0-9a-f]{8}$' and entry_date >= date '2026-04-30';
  if n>0 then raise exception 'incomplete: % backfill rows remain in live window', n; end if;

  if (select data->'serialStarts' from public.config where id=1) <> '[{"id": "e4ujqqp", "date": "2026-04-30", "starts": {"cls_royale": 1, "cls_lounge": 1, "cls_prime": 1}, "screenId": "7gwkvh9"}, {"id": "m8xbwh8", "date": "2026-04-30", "starts": {"1u1lpa4": 1, "lp9hi7s": 1, "bsl9hd8": 1}, "screenId": "oxnv3cw"}]'::jsonb
  then raise exception 'serialStarts rebase did not apply'; end if;
end $$;
